# Build konfigurace pro AI Terminal add-on

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19

labels:
  org.opencontainers.image.title: AI Terminal
  org.opencontainers.image.description: Webovy terminal s Claude CLI a AI agentem pro Home Assistant
  org.opencontainers.image.source: https://github.com/Smitacek/ai-terminal-addon
  org.opencontainers.image.authors: Smitacek
  org.opencontainers.image.licenses: MIT

args:
  BUILD_ARCH: amd64
